document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted SST Storage Management packages
  description: Unwanted SST Storage Management and Components
  maintainer: sst_storage_management
  unwanted_packages:
    - cryptsetup-reencrypt
    - libblockdev-vdo
    - libblockdev-vdo-devel
    - libhbaapi
    - libhbalinux
    - libstoragemgmt-smis-plugin
    - python3-pywbem
    - udisks2-zram
  labels:
    - eln
    - c10s
